"""created at added to advert

Revision ID: 3a66a16213a8
Revises: a1bd58a8ad79
Create Date: 2023-08-05 15:38:41.523909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a66a16213a8'
down_revision = 'a1bd58a8ad79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adverts', 'created_at')
    # ### end Alembic commands ###
