"""added fadvert table

Revision ID: a1bd58a8ad79
Revises: b4bac84ec8d0
Create Date: 2023-08-04 17:44:28.769496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bd58a8ad79'
down_revision = 'b4bac84ec8d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fadverts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_id'], ['adverts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fadverts_id'), 'fadverts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fadverts_id'), table_name='fadverts')
    op.drop_table('fadverts')
    # ### end Alembic commands ###
